name: Flutter CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  Build_Android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
            java-version: "17.x"

      - name: Setup Flutter
        uses: subosito/Flutter-action@v2
        with:
            channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: List build folder (for debugging)
        run: ls -al build/app/outputs/flutter-apk/

      - name: Upload Android APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK to Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.TOKEN }}
          tag: v0.0.1-${{ github.run_number }}
          name: Release v1.0.0
          body: |
            This is an automatically generated release for the **${{ github.ref_name }}** branch.
          draft: false
          prerelease: false

      - name: Rename APK file with version and run number
        run: |
          VERSION_NAME="v1.0.0-${{ github.run_number }}"
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/crm-$VERSION_NAME.apk


      - name: Upload APK to AWS S3 Bucket
        uses: jakejarvis/s3-sync-action@master

        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1' 
          SOURCE_DIR: 'build/app/outputs/flutter-apk'

      - name: Generate pre-signed APK URL
        id: presign
        run: |
          URL=$(aws s3 presign s3://${{ secrets.S3_BUCKET_NAME }}/app-release.apk --expires-in 86400)
          echo "PRE_SIGNED_URL=$URL" >> "$GITHUB_OUTPUT"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'

      - name: Notify Slack with APK URL
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \"🚀 New $VERSION_NAME CRM app APK build available:\n\n<${{ steps.presign.outputs.PRE_SIGNED_URL }}>\"
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
